source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'scribbleNative' do
	pod 'Starscream', '~> 3.0.5'
	pod 'JPSVolumeButtonHandler'
    	pod 'Alamofire', '~> 4.7'
    	pod 'SwiftyJSON', '~> 4.0'
	pod 'CocoaAsyncSocket'
end
